import { useEffect, useState } from 'react'
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'
import { Heart, History, Search, Star, LogOut } from 'lucide-react'
import api from './lib/api'

const image = path => path ? `/api/images/w500/${path.replace('/', '')}` : 'https://placehold.co/500x750/161d30/ffffff?text=No+Poster'
const fetcher = path => api.get(path).then(r => r.data)

function MovieCard({ movie, action }) { return <article className="glass-card overflow-hidden rounded-xl"><Link to={`/movie/${movie.id}`}><img className="h-72 w-full object-cover" src={image(movie.poster_path)} alt={movie.title}/></Link><div className="p-4"><Link to={`/movie/${movie.id}`}><h3 className="truncate font-semibold hover:text-emerald-300">{movie.title}</h3></Link><p className="mt-1 text-xs text-slate-400">{movie.release_date?.slice(0,4) || 'Upcoming'} · <Star className="inline size-3 fill-amber-400 text-amber-400"/> {movie.vote_average?.toFixed?.(1)}</p>{action && <div className="mt-3 flex gap-2">{action}</div>}</div></article> }
function MovieRow({ title, endpoint }) { const {data, isLoading, error} = useQuery({queryKey:[endpoint],queryFn:()=>fetcher(endpoint)}); return <section className="mt-12"><h2 className="mb-4 text-xl font-bold">{title}</h2>{isLoading ? <p>Loading movies…</p> : error ? <p className="text-red-400">Connect TMDB to load this section.</p> : <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{data.results?.slice(0,10).map(m=><MovieCard key={m.id} movie={m}/>)}</div>}</section> }
function MovieDetail(){const {id}=useParams();const {data:movie,isLoading}=useQuery({queryKey:['movie',id],queryFn:()=>fetcher('/movies/'+id)});const [message,setMessage]=useState('');const action=async(path)=>{try{await api.post(path);setMessage('Saved successfully.')}catch(e){setMessage('Log in to use this feature.')}};if(isLoading)return <p>Loading movie…</p>;if(!movie)return <p>Movie not found.</p>;return <section><div className="glass-panel rounded-2xl p-8"><p className="text-emerald-300">{movie.release_date?.slice(0,4)} · {movie.runtime||'—'} minutes</p><h1 className="mt-2 text-4xl font-extrabold">{movie.title}</h1><p className="mt-5 max-w-3xl text-slate-300">{movie.overview}</p><div className="mt-6 flex flex-wrap gap-2">{movie.genres?.map(g=><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-sm text-emerald-200" key={g.id}>{g.name}</span>)}</div><div className="mt-7 flex gap-3"><button onClick={()=>action('/watchlist/'+id)} className="rounded-lg bg-emerald-400 px-4 py-2 font-bold text-slate-950">Add to watchlist</button><button onClick={()=>action('/history/'+id)} className="rounded-lg border border-white/20 px-4 py-2">Mark watched</button></div>{message&&<p className="mt-3 text-emerald-300">{message}</p>}</div></section>}
function SearchPage(){const [q,setQ]=useState('');const [result,setResult]=useState([]);async function submit(e){e.preventDefault();setResult((await fetcher('/movies/search?query='+encodeURIComponent(q))).results||[])}return <section><h1 className="text-3xl font-bold">Search movies</h1><form className="mt-6 flex gap-2" onSubmit={submit}><input className="glass-input flex-1 rounded-xl px-4" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by title"/><button className="rounded-xl bg-emerald-400 px-5 text-slate-950"><Search/></button></form><div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{result.map(m=><MovieCard key={m.id} movie={m}/>)}</div></section>}
function Recommendations(){const params=new URLSearchParams(location.search);const [prompt,setPrompt]=useState(params.get('prompt')||'');const [data,setData]=useState(null);const [error,setError]=useState('');async function run(e){e?.preventDefault();setError('');try{setData((await api.post('/recommendations/ai',{prompt})).data)}catch(err){setError(err.response?.data?.message||'Please log in and make sure the backend and AI service are running.')}}useEffect(()=>{if(prompt)run()},[]);return <section><h1 className="text-3xl font-bold">AI recommendations</h1><form onSubmit={run} className="mt-6 flex gap-2"><input className="glass-input flex-1 rounded-xl px-4 py-3" value={prompt} onChange={e=>setPrompt(e.target.value)}/><button className="rounded-xl bg-emerald-400 px-5 text-slate-950">Recommend</button></form>{error&&<p className="mt-4 text-red-400">{error}</p>}{data&&<><p className="mt-5 text-slate-300">Parsed by {data.parsedPrompt.source}: {data.parsedPrompt.genres_include?.join(', ')||'your preferences'}</p><div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{data.recommendations.map(({movie,reasons})=><MovieCard key={movie.id} movie={movie} action={<span className="text-xs text-emerald-300">{reasons[0]}</span>}/>)}</div></>}</section>}
function Auth(){const [register,setRegister]=useState(false),[form,setForm]=useState({username:'',email:'',password:''}),[message,setMessage]=useState('');const nav=useNavigate();async function submit(e){e.preventDefault();try{const {data}=await api.post(register?'/auth/register':'/auth/login',form);localStorage.setItem('cinematch_token',data.token);localStorage.setItem('cinematch_user',JSON.stringify(data.user));nav('/')}catch(e){setMessage(e.response?.data?.message||'Unable to sign in')}}return <section className="mx-auto max-w-md glass-panel rounded-2xl p-8"><h1 className="text-2xl font-bold">{register?'Create account':'Welcome back'}</h1><form onSubmit={submit} className="mt-6 space-y-3">{register&&<input className="glass-input w-full rounded-xl p-3" placeholder="Username" onChange={e=>setForm({...form,username:e.target.value})}/>}<input className="glass-input w-full rounded-xl p-3" placeholder="Email" type="email" onChange={e=>setForm({...form,email:e.target.value})}/><input className="glass-input w-full rounded-xl p-3" placeholder="Password" type="password" onChange={e=>setForm({...form,password:e.target.value})}/><button className="w-full rounded-xl bg-emerald-400 py-3 font-bold text-slate-950">{register?'Create account':'Log in'}</button></form>{message&&<p className="mt-3 text-red-400">{message}</p>}<button className="mt-5 text-sm text-emerald-300" onClick={()=>setRegister(!register)}>{register?'Already have an account? Log in':'New here? Create an account'}</button></section>}
function Profile(){const {data:watch=[]}=useQuery({queryKey:['watch'],queryFn:()=>fetcher('/watchlist')});const {data:history=[]}=useQuery({queryKey:['history'],queryFn:()=>fetcher('/history')});return <section><h1 className="text-3xl font-bold">My collection</h1><h2 className="mt-8 flex gap-2 text-xl font-bold"><Heart/> Watchlist</h2><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{watch.map(m=><MovieCard key={m.id} movie={m}/>)}</div><h2 className="mt-10 flex gap-2 text-xl font-bold"><History/> Watched</h2><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{history.map(m=><MovieCard key={m.id} movie={m}/>)}</div></section>}
function CineMatchHome(){const [prompt,setPrompt]=useState('');const nav=useNavigate();return <><section className="cinema-hero"><div className="cinema-sparkle">✦</div><h1>Find your next great movie</h1><p>Describe a mood, era, genre, or movie you love. CineMatch turns it into personal recommendations.</p><form onSubmit={e=>{e.preventDefault();if(prompt.trim())nav('/recommend?prompt='+encodeURIComponent(prompt))}} className="cinema-prompt"><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Mind-bending sci-fi like Interstellar, no horror"/><button>Ask AI</button></form></section><MovieRow title="Trending this week" endpoint="/movies/trending"/><MovieRow title="Popular movies" endpoint="/movies/popular"/></>}
function Layout(){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('cinematch_user')||'null'));return <><nav className="glass-nav sticky top-0 z-10"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link to="/" className="text-xl font-extrabold text-emerald-300">CineMatch</Link><div className="flex items-center gap-4 text-sm"><Link to="/search">Search</Link><Link to="/recommend">AI Match</Link>{user?<><Link to="/profile">My Collection</Link><button onClick={()=>{localStorage.clear();setUser(null)}} title="Log out"><LogOut className="size-4"/></button></>:<Link className="rounded-lg bg-emerald-400 px-3 py-2 font-bold text-slate-950" to="/auth">Log in</Link>}</div></div></nav><main className="mx-auto max-w-7xl px-5 py-10"><Routes><Route path="/" element={<CineMatchHome/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/recommend" element={<Recommendations/>}/><Route path="/movie/:id" element={<MovieDetail/>}/><Route path="/auth" element={<Auth/>}/><Route path="/profile" element={<Profile/>}/></Routes></main></>}
const queryClient=new QueryClient(); export default function App(){return <QueryClientProvider client={queryClient}><BrowserRouter><Layout/></BrowserRouter></QueryClientProvider>}
